version: "3.0"

services:

  api:
    build:
      context: .
    image: <%=projectName %>
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
<% if (hasDepends) { -%>
    links:
<% } -%>
<% if (transporter == "NATS") { -%>
      - nats
<% } -%>
<% if (redis) { -%>
      - redis
<% } -%>
<% if (transporter == "MQTT") { -%>
      - mqtt
<% } -%>
<% if (transporter == "AMQP") { -%>
      - amqp
<% } -%>
<% if (transporter == "STAN") { -%>
      - stan
<% } -%>
<% if (transporter == "Kafka") { -%>
      - zookeeper
<% } -%>
<% if (hasDepends) { -%>
    depends_on:
<% } -%>
<% if (transporter == "NATS") { -%>
      - nats
<% } -%>
<% if (redis) { -%>
      - redis
<% } -%>
<% if (transporter == "MQTT") { -%>
      - mqtt
<% } -%>
<% if (transporter == "AMQP") { -%>
      - amqp
<% } -%>
<% if (transporter == "STAN") { -%>
      - stan
<% } -%>
<% if (transporter == "Kafka") { -%>
      - zookeeper
<% } -%>
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  greeter:
    build:
      context: .
    image: <%=projectName %>
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
<% if (hasDepends) { -%>
    links:
<% } -%>
<% if (transporter == "NATS") { -%>
      - nats
<% } -%>
<% if (redis) { -%>
      - redis
<% } -%>
<% if (transporter == "MQTT") { -%>
      - mqtt
<% } -%>
<% if (transporter == "AMQP") { -%>
      - amqp
<% } -%>
<% if (transporter == "STAN") { -%>
      - stan
<% } -%>
<% if (transporter == "Kafka") { -%>
      - zookeeper
<% } -%>
<% if (hasDepends) { -%>
    depends_on:
<% } -%>
<% if (transporter == "NATS") { -%>
      - nats
<% } -%>
<% if (redis) { -%>
      - redis
<% } -%>
<% if (transporter == "MQTT") { -%>
      - mqtt
<% } -%>
<% if (transporter == "AMQP") { -%>
      - amqp
<% } -%>
<% if (transporter == "STAN") { -%>
      - stan
<% } -%>
<% if (transporter == "Kafka") { -%>
      - zookeeper
<% } -%>

<% if (transporter == "NATS") { -%>

  nats:
    image: nats
<% } -%>
<% if (redis) { -%>

  redis:
    image: redis:alpine
<% } -%>
<% if (transporter == "MQTT") { -%>

  mqtt:
    image: ncarlier/mqtt
<% } -%>
<% if (transporter == "AMQP") { -%>

  rabbit:
    image: rabbitmq:3
<% } -%>
<% if (transporter == "STAN") { -%>

  stan:
    image: nats-streaming
<% } -%>
<% if (transporter == "Kafka") { -%>

  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
<% } -%>

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
